stages:
  - build
  - deploy

build:
  stage: build
  image: node:16
  script:
    - npm install
    - npm run build --prod
  artifacts:
    paths:
      - dist/

deploy:
  stage: deploy
  script:
    - mkdir public
    - cp -r dist/* public/
  artifacts:
    paths:
      - public
  environment:
    name: production
    url: https://nazar-koliada-lab.gitlab.io/info-page-nazar-koliada/
  only:
    - master